from __future__ import annotations

import re

from ._model import (
    ContractModel,
    EnumContract,
    MessageContract,
    ServiceContract,
    StreamKind,
)

_COMMON = "common"
_TIMESTAMP_IMPORT = "google/protobuf/timestamp.proto"
_HEADER = "// Code generated by `xime grpc generate`. DO NOT EDIT.\n"


class ProtoEmitter:
    """Renders a ContractModel to deterministic .proto text, one file per stem.

    Output is sorted (messages, enums, services, fields) so `xime grpc check`
    can compare a fresh render byte-for-byte with what is on disk.
    Output được sắp xếp ổn định để `xime grpc check` so sánh từng byte.
    """

    def emit(self, model: ContractModel) -> dict[str, str]:
        """Return {relative_path: proto_text}, e.g. {'public/user.proto': '...'}."""
        file_of = self._file_placement(model)

        # Bucket messages / enums / services per file stem.
        msgs_by_file: dict[str, list[MessageContract]] = {}
        enums_by_file: dict[str, list[EnumContract]] = {}
        for name, msg in model.messages.items():
            msgs_by_file.setdefault(file_of[name], []).append(msg)
        for name, en in model.enums.items():
            enums_by_file.setdefault(file_of[name], []).append(en)

        svc_by_file: dict[str, list[ServiceContract]] = {}
        for svc in model.services:
            svc_by_file.setdefault(self._stem(svc.proto_file), []).append(svc)

        stems = set(msgs_by_file) | set(enums_by_file) | set(svc_by_file)
        files: dict[str, str] = {}
        for stem in sorted(stems):
            text = self._emit_file(
                model,
                stem,
                sorted(enums_by_file.get(stem, []), key=lambda e: e.name),
                sorted(msgs_by_file.get(stem, []), key=lambda m: m.name),
                sorted(svc_by_file.get(stem, []), key=lambda s: s.name),
                file_of,
            )
            files[f"{model.server_id}/{stem}.proto"] = text
        return files

    # ------------------------------------------------------------------
    # File placement (shared → common)
    # ------------------------------------------------------------------

    def _file_placement(self, model: ContractModel) -> dict[str, str]:
        placement: dict[str, str] = {}
        for name in list(model.messages) + list(model.enums):
            stems = model.references.get(name, set())
            if len(stems) > 1:
                placement[name] = _COMMON
            elif stems:
                placement[name] = next(iter(stems))
            else:
                placement[name] = _COMMON  # unreferenced — park in common
        return placement

    # ------------------------------------------------------------------
    # File rendering
    # ------------------------------------------------------------------

    def _emit_file(
        self,
        model: ContractModel,
        stem: str,
        enums: list[EnumContract],
        messages: list[MessageContract],
        services: list[ServiceContract],
        file_of: dict[str, str],
    ) -> str:
        lines: list[str] = [_HEADER, 'syntax = "proto3";', ""]
        lines.append(f"package {self._package(model.server_id)};")
        lines.append("")

        for imp in self._imports(stem, enums, messages, services, model, file_of):
            lines.append(f'import "{imp}";')
        if self._imports(stem, enums, messages, services, model, file_of):
            lines.append("")

        for en in enums:
            lines.append(self._emit_enum(en))
            lines.append("")
        for msg in messages:
            lines.append(self._emit_message(msg))
            lines.append("")
        for svc in services:
            lines.append(self._emit_service(svc))
            lines.append("")

        return "\n".join(lines).rstrip("\n") + "\n"

    def _imports(
        self,
        stem: str,
        enums: list[EnumContract],
        messages: list[MessageContract],
        services: list[ServiceContract],
        model: ContractModel,
        file_of: dict[str, str],
    ) -> list[str]:
        imports: set[str] = set()
        needs_common = False

        for msg in messages:
            for f in msg.fields:
                if "google.protobuf.Timestamp" in f.proto_type:
                    imports.add(_TIMESTAMP_IMPORT)
                for ref in self._type_names(f.proto_type):
                    if ref in file_of and file_of[ref] == _COMMON and stem != _COMMON:
                        needs_common = True

        # Service request/response messages may live in common.
        for svc in services:
            for m in svc.methods:
                for ref in (m.request_message, m.response_message):
                    if file_of.get(ref) == _COMMON and stem != _COMMON:
                        needs_common = True

        if needs_common:
            imports.add(f"{_COMMON}.proto")
        return sorted(imports)

    # ------------------------------------------------------------------
    # Element rendering
    # ------------------------------------------------------------------

    def _emit_enum(self, en: EnumContract) -> str:
        lines = [f"enum {en.name} {{"]
        for v in sorted(en.values, key=lambda x: x.number):
            lines.append(f"  {v.name} = {v.number};")
        lines.append("}")
        return "\n".join(lines)

    def _emit_message(self, msg: MessageContract) -> str:
        lines = [f"message {msg.name} {{"]

        for num in sorted(set(msg.reserved_numbers)):
            lines.append(f"  reserved {num};")
        if msg.reserved_names:
            names = ", ".join(f'"{n}"' for n in sorted(set(msg.reserved_names)))
            lines.append(f"  reserved {names};")

        standalone = [f for f in msg.fields if f.oneof is None]
        for f in sorted(standalone, key=lambda x: x.number):
            opt = "optional " if f.optional else ""
            lines.append(f"  {opt}{f.proto_type} {f.name} = {f.number};")

        # Group oneof fields by their oneof name.
        oneof_groups: dict[str, list] = {}
        for f in msg.fields:
            if f.oneof is not None:
                oneof_groups.setdefault(f.oneof, []).append(f)
        for oneof_name in sorted(oneof_groups):
            lines.append(f"  oneof {oneof_name} {{")
            for f in sorted(oneof_groups[oneof_name], key=lambda x: x.number):
                lines.append(f"    {f.proto_type} {f.name} = {f.number};")
            lines.append("  }")

        lines.append("}")
        return "\n".join(lines)

    def _emit_service(self, svc: ServiceContract) -> str:
        lines = [f"service {svc.name} {{"]
        for m in sorted(svc.methods, key=lambda x: x.rpc_name):
            req = m.request_message
            resp = m.response_message
            if m.kind is StreamKind.CLIENT_STREAM:
                req = f"stream {req}"
            elif m.kind is StreamKind.SERVER_STREAM:
                resp = f"stream {resp}"
            lines.append(f"  rpc {m.rpc_name}({req}) returns ({resp});")
        lines.append("}")
        return "\n".join(lines)

    # ------------------------------------------------------------------
    # Helpers
    # ------------------------------------------------------------------

    @staticmethod
    def _type_names(proto_type: str) -> set[str]:
        """Extract candidate message/enum names from a proto field type string."""
        t = proto_type
        if t.startswith("repeated "):
            t = t[len("repeated "):]
        if t.startswith("map<") and t.endswith(">"):
            inner = t[4:-1]
            parts = [p.strip() for p in inner.split(",")]
            return {p for p in parts}
        return {t}

    @staticmethod
    def _stem(proto_file: str) -> str:
        return proto_file[:-len(".proto")] if proto_file.endswith(".proto") else proto_file

    @staticmethod
    def _package(server_id: str) -> str:
        return f"xime.{re.sub(r'[^0-9a-zA-Z_]', '_', server_id)}"
